# Generated by Django 3.2.6 on 2021-12-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20211210_1250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question1',
        ),
        migrations.DeleteModel(
            name='Question2',
        ),
    ]
