# Generated by Django 3.2.6 on 2021-12-09 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('quiz', '0002_alter_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Name',
        ),
    ]
