# Generated by Django 3.2.6 on 2021-12-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quiz', '0004_question1_question2'),
    ]

    operations = [
        migrations.AddField(
            model_name='question1',
            name='correct',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='question2',
            name='correct',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
