# Generated by Django 3.2.6 on 2021-12-11 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_choices_question_quizhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question1',
        ),
        migrations.DeleteModel(
            name='Question2',
        ),
    ]
